#!/bin/bash
set -e

# Update man pages
mandb -q || true

# Update services
deb-systemd-helper enable backlight-tracer || true
deb-systemd-invoke start backlight-tracer || systemctl start backlight-tracer

# Done
exit 0
