#!/bin/bash
set -e

rm /usr/bin/backlight-increase || true
rm /usr/bin/backlight-decrease || true

deb-systemd-invoke stop backlight-tracer || systemctl stop backlight-tracer
deb-systemd-helper disable backlight-tracer

exit 0
