.\" Manpage for Backlight Tracer
.\" Contact jmedved@jmedved.com to correct errors or typos.
.TH BACKLIGHT-TRACER 1 "28 Dec 2019" "MAJOR.MINOR.PATCH" "backlight-tracer man page"


.SH NAME

backlight-tracer \- Tracking backlight brightness over power changes


.SH SYNOPSIS

.ad l
\fBbacklight-tracer\fR


.SH DESCRIPTION

It remembers backlight brightness an restores it upon power state change.


.SH AUTHOR

Josip Medved <jmedved@jmedved.com>
